### ISSUE TITLE
Exception on printing [None]

### ISSUE THREAD

**Issue by melomac** [CouleeApps/hex_integers#3]
Thank you very much for creating and distributing the `hex_integers` plugin, it is so helpful!

Would you please be so kind to consider preventing this reproducible exception:

```
>>> [None]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/noar/Library/Application Support/Binary Ninja/repositories/community/plugins/CouleeApps_hex_integers/__init__.py", line 73, in new_displayhook
    result = convert_to_hexint(value, [], True)
  File "/Users/noar/Library/Application Support/Binary Ninja/repositories/community/plugins/CouleeApps_hex_integers/__init__.py", line 45, in convert_to_hexint
    return '[' + ', '.join(convert_to_hexint(v, seen) for v in value) + ']'
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by CouleeApps** [comment]
Fixed in v1.9. Thanks for the report.
